# Uncomment any patches here for which you wish to enable specific features for hardware testing
FILESEXTRAPATHS_prepend := "${THISDIR}/smarc-rzg2l:"
#SRC_URI += "file://0001-add-vsc8531-userspace-dts.patch"
#SRC_URI += "file://0002-add-sx150x-port-expander-dts.patch"
#SRC_URI += "file://0003-add-gpio-header-40-pin-dts.patch"
#SRC_URI += "file://0004-add-RSPI0-port-to-40-pin-header.patch"
#SRC_URI += "file://0005-add-scif2-serial-port-for-uart-testing.patch"
#SRC_URI += "file://0006-add-riic1-i2c1-for-testing-i2c-on-hdr.patch"
#SRC_URI += "file://0007-add-can-ports.patch"
FILESEXTRAPATHS_prepend := "${THISDIR}/smarc-rzv2l:"
#SRC_URI += "file://0008-add-vsc8531-userspace-dts.patch"
#SRC_URI += "file://0009-add-sx150x-port-expander-dts.patch"
#SRC_URI += "file://0010-add-gpio-header-40-pin-dts.patch"
#SRC_URI += "file://0011-add-RSPI0-port-to-40-pin-header.patch"
#SRC_URI += "file://0012-add-scif2-serial-port-for-uart-testing.patch"
#SRC_URI += "file://0013-add-riic1-i2c1-for-testing-i2c-on-hdr.patch"
#SRC_URI += "file://0014-add-can-ports.patch"

FILESEXTRAPATHS_prepend := "${THISDIR}/Kconfigs:"
SRC_URI += "file://ATH6KL.cfg"
SRC_URI += "file://FB_UDL.cfg"
SRC_URI += "file://GT9271.cfg"
SRC_URI += "file://RTL8152.cfg"
SRC_URI += "file://TLV320AIC23.cfg"
SRC_URI += "file://VSC8531.cfg"
SRC_URI += "file://WIRELESS.cfg"
