name: Build Yocto Image

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
jobs:
  build-yocto:
    runs-on: DC02
    
    steps:    
    - uses: actions/checkout@v3
      with:
        repository: MistySOM/rzg2l
        path: rzg2l
        ref: develop
        submodules: true

    - uses: actions/checkout@v3
      with:
        path: meta-mistysom

    - run: |
        rm -rf rzg2l/Build/meta-mistysom
        cp -r meta-mistysom rzg2l/Build/

    - name: Build the Docker image
      run: cd rzg2l/Build && ./build.sh;
    
    - name: Run the Docker image and build output files with SDK
      run: cd rzg2l/Build && ./run.sh -c /home/github/rzg2l-cache;

    - name: List files that are generated
      run: ls -lah rzg2l/Build/output/images/smarc-rzg2l/
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: output-files
        path: rzg2l/Build/output/images/smarc-rzg2l/mistysom-image-smarc-rzg2l.wic.bz2
