name: Create release promotion pull request
on:
  push:
    branches:
      - develop
jobs:
  release-promotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - name: Reset develop branch
        run: |
          git fetch origin develop:develop
          git reset --hard develop
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: master
          token: ${{ secrets.PAT }}
          team-reviewers: reviewers
